ci:
  autoupdate_schedule: quarterly
  autoupdate_branch: 'main'
  autofix_prs: false
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-added-large-files
        - id: check-ast
        - id: check-merge-conflict
    - repo: https://github.com/kynan/nbstripout
      rev: 0.8.1
      hooks:
        - id: nbstripout
          args:
          # Strip metadata but keep counts and outputs
          - --keep-count
          - --keep-output
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.8.6
      hooks:
        - id: ruff
          args:
          - --fix
          types_or:
          - python
          - pyi
          - jupyter
        - id: ruff-format
          types_or:
          - python
          - pyi
          - jupyter
    - repo: https://github.com/glotzerlab/fix-license-header
      rev: v0.4.1
      hooks:
        - id: fix-license-header
          name: Fix License Headers (Python)
          exclude: ^docs/
          types_or: [python]
          args:
            - --license-file=LICENSE
            - --start=2
            - --num=1
            - --add=This file is from the dupin project, released under the BSD 3-Clause License.
            - --keep-before=#!
