repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-added-large-files
        - id: check-ast
        - id: check-merge-conflict
    - repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
         - id: black
           language_version: python3
    - repo: https://gitlab.com/pycqa/flake8
      rev: '3.8.4'
      hooks:
        - id: flake8
    - repo: https://github.com/pycqa/isort
      rev: '5.7.0'
      hooks:
        - id: isort
    - repo: https://github.com/pycqa/pydocstyle
      rev: 5.1.1
      hooks:
        - id: pydocstyle
          files: ^((?!docs|tests).)*$
