version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "mamba-forge-4.10"

conda:
    environment: docs/environment.yml

python:
    install:
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

submodules:
    include: all
    recursive: true
