[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 64.0.0"]

[project]
name = "dupin"
version = "0.2"
description = "Offline and online event detection scheme for rare events in molecular simulations."
readme = "README.rst"
requires-python = ">=3.9"
maintainers = [{name = "Brandon Butler", email = "butlerbr@umich.edu"}]
authors = [{name = "Brandon Butler et al.", email = "butlerbr@umich.edu"}]
keywords = ["event detection", "molecular simulations"]
classifiers = [
        "Development Status :: 4 - Beta",
        "Natural Language :: English",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
    ]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements/requirements.txt"] }
optional-dependencies = { testing = { file = [
    "requirements/requirements-testing.txt",
] } }

[project.urls]
Source = "https://github.com/glotzerlab/dupin"
Documentation = "https://dupin.readthedocs.io"
Issues = "https://github.com/glotzerlab/dupin/issues"

[tool.setuptools]
packages = { find = { namespaces = false, exclude = ["tests*", "notebooks*"] } }

[tool.ruff]
include = ["*.py", "*.ipynb"]
line-length = 80

[tool.ruff.lint]
ignore = ["N803", "N806", "A003", "PLR0913", "E741"]
select = [
    "A",   # flake8-builtins
    "B",   # flake8-bugbear
    "EM",  # flake8-errmsg
    "ICN", # flake8-import-conventions
    "N",   # pep8-naming
    "NPY", # NumPy-specific rules
    "PL",  # Pylint
    "PT",  # flake8-pytest-style
    "RET", # flake8-return
    "RUF", # Ruff specific rules
    "UP",  # pyupgrade
    "E",   # pycodestyle (errors)
    "W",   # pycodestyle (warnings) ruff supports W but, W503 is not supported!!
    "F",   # pyflakes
    "D",   # pydocstyle
    "I",   # isort
]

[tool.ruff.lint.extend-per-file-ignores]
"tests/*" = ["D100", "D101", "D102", "D103", "B008"]
"docs/*" = ["D100", "D101", "D102", "D103", "E501"]
"conftest.py" = ["D401"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.pytest.ini_options]
minversion = "6.0"
filterwarnings = [
    "ignore::UserWarning:dupin.*"
]
