name: dupin-rtd
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.13.2 
  - pip==25.0.1
  - bottleneck==1.4.2
  - freud==3.2.0
  - kneed==0.8.5
  - numpy==2.2.3
  - ruptures==1.0.6
  - scikit-learn==1.6.1
  - pandas==2.2.3
  - sphinx==8.1.3
  - furo==2024.8.6
  - nbsphinx==0.9.6
  - jupyter_sphinx==0.5.3
  - pandoc==3.6.3
