name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-test-publish-to-pypi:
    environment: release
    permissions:
      id-token: write
    uses: ./.github/workflows/publish-packages.yml
    with:
      upload_to_test: false
