name: Publish to TestPyPI

on:
  push:
    branches:
      - 'release/*.*.*'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build-test-publish-to-testpypi:
    environment: release
    permissions:
      id-token: write
    uses: ./.github/workflows/publish-packages.yml
    with:
      upload_to_test: true
