name: Publish to TestPyPI

on:
  # trigger on pull requests
  pull_request:

  # trigger on all commits to main
  push:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        # We must explicitly install the requirements so that we can force
        # installation of the local wheel below in case the version conflicts
        # with published wheels (typically only possible during testing).
        python -m pip install \
        -r requirements/requirements-build.txt \
        -r requirements/requirements.txt \
        -r requirements/requirements-testing.txt

    - name: Install pypa/build
      run:
        python -m pip install build
    - name: Build a binary wheel and a source tarball
      run:
        python -m build --outdir dist/ .
    - name: Install wheel
      run:
        python -m pip install dupin --progress-bar off --no-index -f dist/
    - name: Test with pytest
      run:
        python -m pytest -v tests/

    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/