name: Update uv lockfiles

on:
  schedule:
    - cron: '9 12 1-7 3,6,2,12 4'

  workflow_dispatch:

jobs:
  update:
    uses: glotzerlab/workflows/.github/workflows/update-uv-lockfiles.yaml@1747bc5c994ec280440dd051f2928791407692c8 # 0.5.1
    secrets: inherit
    with:
      branch: main
